#!/usr/bin/env php
<?php

/*
 * This file is part of Rebar.
 *
 * (c) Oliver Green <oliver@c5dev.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/vendor/illuminate/support/helpers.php';

$console = new \C5Dev\Rebar\Application();
$console->run();